root: true
env:
  browser: true
  commonjs: true
  es2020: true
extends:
  - "eslint:recommended"
  - "plugin:vue/essential"
parserOptions:
  ecmaVersion: 11
rules:
  vue/experimental-script-setup-vars: "off"
  no-useless-catch: "off"
  no-undef: "off"
  indent:
    - "error"
    - 2
  eqeqeq:
    - "error"
    - "always"
  camelcase:
    - "error"
  linebreak-style: "off"
  quotes: "off"
  semi:
    - error
    - never
